package SecuringWebApplication;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.authentication.configurers.GlobalAuthenticationConfigurerAdapter;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.config.annotation.web.servlet.configuration.EnableWebMvcSecurity;

@Configuration
@EnableWebMvcSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter{

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		// Home page no authorization need
		http.authorizeRequests().antMatchers("/", "/home").permitAll().anyRequest().authenticated();
		// Login page no authentication either
		http.formLogin().loginPage("/login").permitAll().and().logout().permitAll();
	}
	
	// Create a memory based user-password
	protected static class AuthenticationConfiguration extends 
		GlobalAuthenticationConfigurerAdapter {

		@Override
		// Do not use this "password" as password
		// Use the default security password, which is generated by Spring each time you start the server.
		// Something like "57d92579-f379-4994-868e-688f785c3856"
		public void init(AuthenticationManagerBuilder auth) throws Exception {
			auth.inMemoryAuthentication().withUser("user").password("password").roles("USER");
		}
	}
}
